### ISSUE TITLE
Страница проекта

### ISSUE THREAD

**Issue by tngme** [AntFilin/lessonsphp#1]
1) Создать в любом удобном виде страницу проекта.
Страница будет содержать название проекта, ваши идеи о проекте, контакты.

2) Аналогичную информацию размести в файл README.md
Этот файл предназначен для других людей, которые зайдут на твой репозиторий и захотят почерпнуть больше информации о проекте.

3) У тебя в репозитории хранится папка .idea. Это неправильно, так как настройки программы не должны хранится в общем репозитории, так как у каждого свои настройки + может кто-то использует Sublime или другой PHP-редактор. 
Preferences - Version Control - Ignored Files, добавь сюда всю папку с настройками.

**Comment by tngme** [comment]
Фичи будущего проекта:
1) Регистрация / авторизация пользователя
2) Привилегии (гость, пользователь, автор блога)
3) Создание/редактирование статьи
4) Объединение статей в рубрики
5) Тегирование статей
6) Список статей
6) Поиск статей (по рубрики, по тегу, по названию)

**Comment by AntFilin** [comment]
Сделано: https://github.com/AntFilin/lessonsphp/issues/1#issue-116941574
