### ISSUE TITLE
Страница с публикациями

### ISSUE THREAD

**Issue by tngme** [AntFilin/lessonsphp#2]
Создать файл post.php.

Внутри файла создать массив, который будет содержать все публикации, включая заголовок публикации и тело публикации.

Имя массива – $posts.
Он представляет из себя простой массив ассоциативных массивов, каждый элемент массива имеет структуру ['title','body'].

Создать страницу с публикациями (post.html.php).
Для дизайна использовать Bootstrap (http://getbootstrap.com/).
Каждый пост будет состоять из панели (http://getbootstrap.com/components/#panels-heading).

Из файла post.php подключить файл post.html.php. Пройтись циклом по массиву $posts, вывести все публикации на страницу.

**Comment by AntFilin** [comment]
Исходя из текста задачи, что удалось выполнить:
-создан файл post.php
-внутри файла, подключен файл post.html.php
-создан массив $posts
-использован цикл foreach и вывод на страницу (есть сомнения в правильности)
-создан файл post.html.php, в нем подключен bootstrap v3.3.5 и создана одна панелька.

**Comment by tngme** [comment]
1) https://github.com/AntFilin/lessonsphp/blob/master/post.html.php#L6

Ты тут подключил файл стилей, но у меня его нет. Поэтому мне пришлось создать папку css и загрузить туда эти стили. Это плохо, так как в проекте с 1000 файлами этим никто заниматься не будет. Помести свою папку css в систему контроля версий.

2) https://github.com/AntFilin/lessonsphp/blob/master/post.php#L9

Объясню логику: ты подключаешь файл post.html.php, все содержимое файла post.html.php вставляется в файл post.php, потом ты начинаешь выводить циклом еще что-то.
То есть браузер уже не ожидает, что ниже тега html что-то будет.
Как это исправить - напишу чуть ниже.

3) https://github.com/AntFilin/lessonsphp/blob/master/post.php#L11-L16

Да, почти правильно, только titile и body - это ключи ассоциативного массива со своим уникальным содержимым. Плюс не обязательно каждому посту делать свой ключ.
 Поэтому:

``` php
$posts = array(
array ('title' => 'title of post1','body' => 'body of post1'),
array ('title' => 'title of post2','body' => 'body of post2')
);
```

таким образом у нас есть массив постов, каждый элемент который по ключу title имеет заголовок, а по ключу body - тело.

4) https://github.com/AntFilin/lessonsphp/blob/master/post.php#L19-L23

Не используй никогда echo. Файл post.php является контроллером, то есть некоторым управляющим звеном. Файл post.html.php является видом (view), и он отвечает за вывод чего-то на экран. Поэтому если тебе что-то надо вывести, то только во вьюхе, контроллер отвечает за подготовку данных для вывода.

5) Исходя из (4) и (2) становится понятно, что цикл нужно перенести в файл post.html.php
Приведу пример:

``` php
<?php foreach($posts as $post) { ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"> <?php echo $post['title']; ?> </h3>
    </div>
    <div class="panel-body">
        <h3 class="panel-title"><?php echo $post['body']; ?>
    </div>
</div>
<?php } ?>
```

То есть мы будем проходить по циклу и каждый раз создавать новую панель. Внутри цикла мы будем выводить по ключу заголовок и тело.

Не забудь, что подключить файл post.html.php необходимо после того, как массив будет создан, то есть в самом конце файла post.php

6) Создай папку post и перемести эти 2 файла в эту папку. Чтобы в будущем мы не терялись в однообразных файлах.

**Comment by AntFilin** [comment]
Учел замечания, ошибки исправил.

**Comment by tngme** [comment]
1) Убери дублирование одного поста в файле post.html.php.
2) Давай познакомимся с такой угрозой безопасности как XSS
https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B6%D1%81%D0%B0%D0%B9%D1%82%D0%BE%D0%B2%D1%8B%D0%B9_%D1%81%D0%BA%D1%80%D0%B8%D0%BF%D1%82%D0%B8%D0%BD%D0%B3

Попробуй вместо 'title of post 1' вставить какой-то html код, например 

```
<script>alert(1);</script>
```

Если ты обновишь страницу, то тебе выведется окно с цифрой 1. Это мы вставили JavaScript вместо тела публикации.

То есть любой пользователь, который захочет написать пост сможет вставить любой HTML или JavaScript код. Это естественно очень плохо. Для этого существует функция htmlspecialchars(), она преобразовывает специальные символы и в браузер они подадутся в виде обычно текста, а не как код.

Поэтому везде при любом выводе необходимо преобразовывать все переменные значения.

Пример: htmlspecialchars($post['body'])

**Comment by AntFilin** [comment]
1) Убрал дублирование.
2) Проверил на своем проекте, в файле post.html.php внес изменения с использованием функции htmlspecialchars.

**Comment by AntFilin** [comment]
Задача выполнена.
