### ISSUE TITLE
Создание БД

### ISSUE THREAD

**Issue by tngme** [AntFilin/lessonsphp#4]
- Установить и настроить MySQL
- Через консоль войти на MySQL сервер, создать БД с именем blog
- Создать таблицу posts, состоять будет из 4 полей 
  - первичный ключ post_id, который будет иметь уникальное значение ( bigint unsigned not null auto_increment primary key)
  - дата публикации dt_post (datetime not null)
  - тело публикации s_body (longtext)
  - заголовок публикацим s_title (text)
- создать несколько записей при помощи запроса insert into ..
- в файле post.php заполнить массив posts значениями из базы данных (сейчас у нас просто вручную занесенные значения)

Что почитать:
http://www.site-do.ru/db/db.php (ознакомиться с Основы баз данных, ознакомиться с Уроки SQL 1-4 урок)
http://php.net/manual/ru/book.mysql.php (ознакомиться)

**Comment by AntFilin** [comment]
- Установил и настроил работу MySQL.
- Создал БД по заданию.
- Сделал отдельный файл для подключения к БД. Пока оставил в нем вывод сообщения об успешном подключении к базе данных. !(для наглядности, пока учусь, потом его уберу)

Разобрался с запросами к БД, остается с выводом результатов и заполнением массива posts.
С последним моментом есть затруднения, продолжаю разбираться.

**Comment by AntFilin** [comment]
Выполнил все требования по задаче. 
Есть локальные проблемы с отображением текстовых символов из БД.
